### ISSUE TITLE
首次启动服务端时，创建表语句报错

### ISSUE THREAD

**Issue by shawfix** [773579084/Leno_Admin#1]
@773579084 `/leno-admin/backend` 项目中 `sys_menu.order_num` 的类型错误：
```
Executing (default): CREATE TABLE IF NOT EXISTS `sys_menu` (`menu_id` BIGINT NOT NULL auto_increment UNIQUE  COMMENT '菜单ID', `menu_name` VARCHAR(255) NOT NULL COMMENT '菜单名称', `parent_id` BIGINT DEFAULT 0 COMMENT '父菜单ID', `order_num` INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路由地址', `component` CHAR(255) COMMENT '组件路径', `query` CHAR(255) COMMENT '路由参数', `is_frame` CHAR(1) DEFAULT '1' COMMENT '是否为外链（0是 1否）', `is_cache` CHAR(1) DEFAULT '0' COMMENT '是否缓存（0缓存 1不缓存）', `menu_type` CHAR(1) DEFAULT '' COMMENT '菜单类型（M目录 C菜单 F按钮)', `visible` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0显示 1隐藏）', `status` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0正常 1停用）', `perms` CHAR(100) DEFAULT NULL COMMENT '权限标识', `icon` CHAR(100) DEFAULT '' COMMENT '菜单图标', `create_by` CHAR(64) DEFAULT '' COMMENT '创建者', `update_by` CHAR(64) DEFAULT '' COMMENT '更新者', `remark` CHAR(255) COMMENT '备注', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`menu_id`)) ENGINE=InnoDB COMMENT '菜单权限表';
数据库连接失败 Error: 
    at Query.run (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/sequelize/src/dialects/mysql/query.js:46:25)
    at /Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/sequelize/src/sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MySQLQueryInterface.createTable (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/sequelize/src/dialects/abstract/query-interface.js:229:12)
    at Function.sync (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/sequelize/src/model.js:1353:7)
    at Sequelize.sync (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/sequelize/src/sequelize.js:825:9) {
  name: 'SequelizeDatabaseError',
  parent: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路ç' at line 1
      at Packet.asError (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路ç' at line 1",
    sql: "CREATE TABLE IF NOT EXISTS `sys_menu` (`menu_id` BIGINT NOT NULL auto_increment UNIQUE  COMMENT '菜单ID', `menu_name` VARCHAR(255) NOT NULL COMMENT '菜单名称', `parent_id` BIGINT DEFAULT 0 COMMENT '父菜单ID', `order_num` INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路由地址', `component` CHAR(255) COMMENT '组件路径', `query` CHAR(255) COMMENT '路由参数', `is_frame` CHAR(1) DEFAULT '1' COMMENT '是否为外链（0是 1否）', `is_cache` CHAR(1) DEFAULT '0' COMMENT '是否缓存（0缓存 1不缓存）', `menu_type` CHAR(1) DEFAULT '' COMMENT '菜单类型（M目录 C菜单 F按钮)', `visible` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0显示 1隐藏）', `status` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0正常 1停用）', `perms` CHAR(100) DEFAULT NULL COMMENT '权限标识', `icon` CHAR(100) DEFAULT '' COMMENT '菜单图标', `create_by` CHAR(64) DEFAULT '' COMMENT '创建者', `update_by` CHAR(64) DEFAULT '' COMMENT '更新者', `remark` CHAR(255) COMMENT '备注', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`menu_id`)) ENGINE=InnoDB COMMENT '菜单权限表';",
    parameters: undefined
  },
  original: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路ç' at line 1
      at Packet.asError (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/liudaodan/Documents/proj/leno-admin/backend/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路ç' at line 1",
    sql: "CREATE TABLE IF NOT EXISTS `sys_menu` (`menu_id` BIGINT NOT NULL auto_increment UNIQUE  COMMENT '菜单ID', `menu_name` VARCHAR(255) NOT NULL COMMENT '菜单名称', `parent_id` BIGINT DEFAULT 0 COMMENT '父菜单ID', `order_num` INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路由地址', `component` CHAR(255) COMMENT '组件路径', `query` CHAR(255) COMMENT '路由参数', `is_frame` CHAR(1) DEFAULT '1' COMMENT '是否为外链（0是 1否）', `is_cache` CHAR(1) DEFAULT '0' COMMENT '是否缓存（0缓存 1不缓存）', `menu_type` CHAR(1) DEFAULT '' COMMENT '菜单类型（M目录 C菜单 F按钮)', `visible` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0显示 1隐藏）', `status` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0正常 1停用）', `perms` CHAR(100) DEFAULT NULL COMMENT '权限标识', `icon` CHAR(100) DEFAULT '' COMMENT '菜单图标', `create_by` CHAR(64) DEFAULT '' COMMENT '创建者', `update_by` CHAR(64) DEFAULT '' COMMENT '更新者', `remark` CHAR(255) COMMENT '备注', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`menu_id`)) ENGINE=InnoDB COMMENT '菜单权限表';",
    parameters: undefined
  },
  sql: "CREATE TABLE IF NOT EXISTS `sys_menu` (`menu_id` BIGINT NOT NULL auto_increment UNIQUE  COMMENT '菜单ID', `menu_name` VARCHAR(255) NOT NULL COMMENT '菜单名称', `parent_id` BIGINT DEFAULT 0 COMMENT '父菜单ID', `order_num` INET DEFAULT 0 COMMENT '显示顺序', `path` CHAR(255) DEFAULT '' COMMENT '路由地址', `component` CHAR(255) COMMENT '组件路径', `query` CHAR(255) COMMENT '路由参数', `is_frame` CHAR(1) DEFAULT '1' COMMENT '是否为外链（0是 1否）', `is_cache` CHAR(1) DEFAULT '0' COMMENT '是否缓存（0缓存 1不缓存）', `menu_type` CHAR(1) DEFAULT '' COMMENT '菜单类型（M目录 C菜单 F按钮)', `visible` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0显示 1隐藏）', `status` CHAR(1) DEFAULT '0' COMMENT '菜单状态（0正常 1停用）', `perms` CHAR(100) DEFAULT NULL COMMENT '权限标识', `icon` CHAR(100) DEFAULT '' COMMENT '菜单图标', `create_by` CHAR(64) DEFAULT '' COMMENT '创建者', `update_by` CHAR(64) DEFAULT '' COMMENT '更新者', `remark` CHAR(255) COMMENT '备注', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`menu_id`)) ENGINE=InnoDB COMMENT '菜单权限表';",
  parameters: {}
}
```

**Comment by 773579084** [comment]
出现这种情况，可能是因为你的mysql没有leno-admin这个数据库，你可以看下我的文档，将项目中的sql文件导入到MySQL中，应该可以解决这个问题，我之前线上部署时未导入数据库，也报了此错误
